"use client";

const configuredUrl=typeof process!=="undefined"?process.env.NEXT_PUBLIC_POCKETBASE_URL:undefined;
const PB_URL=(configuredUrl||(typeof window!=="undefined"?"/pb":"http://127.0.0.1:8090")).replace(/\/$/,"");
async function request(path:string,init?:RequestInit){const response=await fetch(`${PB_URL}${path}`,{cache:"no-store",...init,headers:{"x-lumina-ui":"local",...(init?.headers||{})}});if(!response.ok){const value=await response.json().catch(()=>null) as {message?:string;data?:Record<string,{message?:string}>}|null;const field=value?.data&&Object.values(value.data).find(item=>item?.message)?.message;throw new Error(field||value?.message||`内容工厂请求失败（HTTP ${response.status}）`)}return response.json()}
export type FactoryProjectInput={id?:string;forkFrom?:string;forkReason?:string;changedParameters?:string[];title:string;dramaId:string;hookId:string;storyMatchId:string;selectedEpisodes:number[];topics:string[];transition:unknown;timeline:unknown[];qualityReport:unknown;review?:unknown;version?:number;ratio:"9:16"|"16:9"|"1:1";language:string;paidScopeConfirmed?:boolean};
export type FactoryProjectRecord={id:string;status:string;version:number};
export type FactoryRenderRecord={id:string;project:string;version:number;status:"queued"|"rendering"|"succeeded"|"failed";progress:number;stage:string;error:string;previewUrl?:string;outputUrl?:string;validation?:unknown};
export type FactoryExportRecord={renderId:string;fileName:string;outputUrl:string;outputSha256:string;exportedAt:string};
export type FactoryHistoryRecord={id:string;title:string;mode:string;drama:string;hook:string;story_match:string;parent_project:string;fork_reason:string;revision_snapshot:Record<string,unknown>;selected_episodes:number[];topics:string[];transition:Record<string,unknown>;timeline:unknown[];quality_report:Record<string,unknown>;review:Record<string,unknown>;version:number;status:string;created:string;updated:string;ratio:"9:16"|"16:9"|"1:1";language:string;latest_render:null|{id:string;version:number;status:string;progress:number;current_stage:string;preview_url:string;output_url:string;validation:unknown};render_versions:Array<{id:string;version:number;status:string;preview_url:string;output_url:string;created:string}>};
export async function saveFactoryProject(input:FactoryProjectInput):Promise<FactoryProjectRecord>{const value=await request("/api/lumina/factory/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:input.id,fork_from:input.forkFrom,fork_reason:input.forkReason,changed_parameters:input.changedParameters,title:input.title,drama_id:input.dramaId,hook_id:input.hookId,story_match_id:input.storyMatchId,selected_episodes:input.selectedEpisodes,topics:input.topics,transition:input.transition,timeline:input.timeline,quality_report:input.qualityReport,review:input.review||{},version:input.version||1,ratio:input.ratio,language:input.language,paid_scope_confirmed:input.paidScopeConfirmed===true})}) as Record<string,unknown>;return{id:String(value.id),status:String(value.status),version:Number(value.version||1)}}
export async function saveEpisodeSpliceProject(input:{id?:string;title:string;dramaId:string;selectedEpisodes:number[];timeline:unknown[];qualityReport:unknown;ratio:"9:16"|"16:9"|"1:1";language:string}):Promise<FactoryProjectRecord>{const value=await request("/api/lumina/factory/episode-splice/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:input.id,title:input.title,drama_id:input.dramaId,selected_episodes:input.selectedEpisodes,timeline:input.timeline,quality_report:input.qualityReport,ratio:input.ratio,language:input.language})}) as Record<string,unknown>;return{id:String(value.id),status:String(value.status),version:Number(value.version||1)}}
export async function startFactoryRender(projectId:string):Promise<FactoryRenderRecord>{const value=await request(`/api/lumina/factory/projects/${encodeURIComponent(projectId)}/renders`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({render_config:{format:"MP4",resolution:"1080x1920",videoCodec:"H.264",audioCodec:"AAC",ratio:"9:16"}})}) as Record<string,unknown>;return{id:String(value.id),project:String(value.project),version:Number(value.version||1),status:String(value.status) as FactoryRenderRecord["status"],progress:0,stage:"queued",error:""}}
export async function getFactoryRender(id:string,signal?:AbortSignal):Promise<FactoryRenderRecord>{const value=await request(`/api/lumina/factory/renders/${encodeURIComponent(id)}`,{signal}) as Record<string,unknown>;return{id:String(value.id),project:String(value.project),version:Number(value.version||1),status:String(value.status) as FactoryRenderRecord["status"],progress:Number(value.progress||0),stage:String(value.current_stage||""),error:String(value.error||""),previewUrl:typeof value.preview_url==="string"?value.preview_url:undefined,outputUrl:typeof value.output_url==="string"?value.output_url:undefined,validation:value.validation}}
export async function reviewFactoryRender(projectId:string,renderId:string,decision:"approved"|"rejected",note:string):Promise<void>{await request(`/api/lumina/factory/projects/${encodeURIComponent(projectId)}/review`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({render_id:renderId,decision,note})})}
export async function exportFactoryRender(projectId:string,renderId:string,fileName:string):Promise<FactoryExportRecord>{return await request(`/api/lumina/factory/projects/${encodeURIComponent(projectId)}/export`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({render_id:renderId,file_name:fileName})}) as FactoryExportRecord}
export async function listFactoryHistory(signal?:AbortSignal):Promise<FactoryHistoryRecord[]>{const value=await request("/api/lumina/factory/history",{signal}) as {items?:FactoryHistoryRecord[]};return value.items??[]}
