"use client";

import { POCKETBASE_URL as PB_URL, pocketBaseUiHeaders } from "./pocketbase-url";
async function request(path:string,init?:RequestInit){const response=await fetch(`${PB_URL}${path}`,{cache:"no-store",...init,headers:{...pocketBaseUiHeaders(),...(init?.headers||{})}});if(!response.ok){const value=await response.json().catch(()=>null) as {message?:string;data?:Record<string,{message?:string}>}|null;const field=value?.data&&Object.values(value.data).find(item=>item?.message)?.message;throw new Error(field||value?.message||`内容工厂请求失败（HTTP ${response.status}）`)}return response.json()}
export type FactoryProjectInput={id?:string;forkFrom?:string;forkReason?:string;changedParameters?:string[];title:string;dramaId:string;hookId:string;storyMatchId:string;selectedEpisodes:number[];topics:string[];transition:unknown;timeline:unknown[];qualityReport:unknown;review?:unknown;version?:number;ratio:"9:16"|"16:9"|"1:1";language:string;paidScopeConfirmed?:boolean};
export type FactoryProjectRecord={id:string;status:string;version:number};
export type FactoryRenderRecord={id:string;project:string;version:number;status:"queued"|"rendering"|"succeeded"|"failed";progress:number;stage:string;error:string;errorKind?:string;updated?:string;retryOf?:string;queuedAt?:string;startedAt?:string;lastHeartbeatAt?:string;leaseUntil?:string;nextAttemptAt?:string;previewUrl?:string;outputUrl?:string;validation?:unknown};
export type FactoryExportRecord={renderId:string;fileName:string;outputUrl:string;outputSha256:string;exportedAt:string};
export type TransitionPreviewRecord={projectId:string;status:"idle"|"queued"|"rendering"|"succeeded"|"failed";renderId?:string;previewUrl?:string;previewVersion?:number;previewHash?:string;transitionVersion?:number;error?:string;transition?:Record<string,unknown>};
export type FactoryHistoryRecord={id:string;title:string;mode:string;drama:string;hook:string;story_match:string;parent_project:string;fork_reason:string;revision_snapshot:Record<string,unknown>;selected_episodes:number[];topics:string[];transition:Record<string,unknown>;timeline:unknown[];quality_report:Record<string,unknown>;review:Record<string,unknown>;version:number;status:string;created:string;updated:string;ratio:"9:16"|"16:9"|"1:1";language:string;latest_render:null|{id:string;version:number;status:string;progress:number;current_stage:string;preview_url:string;output_url:string;validation:unknown};render_versions:Array<{id:string;version:number;status:string;preview_url:string;output_url:string;created:string}>};
export async function saveFactoryProject(input:FactoryProjectInput):Promise<FactoryProjectRecord>{const value=await request("/api/lumina/factory/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:input.id,fork_from:input.forkFrom,fork_reason:input.forkReason,changed_parameters:input.changedParameters,title:input.title,drama_id:input.dramaId,hook_id:input.hookId,story_match_id:input.storyMatchId,selected_episodes:input.selectedEpisodes,topics:input.topics,transition:input.transition,timeline:input.timeline,quality_report:input.qualityReport,review:input.review||{},version:input.version||1,ratio:input.ratio,language:input.language,paid_scope_confirmed:input.paidScopeConfirmed===true})}) as Record<string,unknown>;return{id:String(value.id),status:String(value.status),version:Number(value.version||1)}}
export async function saveEpisodeSpliceProject(input:{id?:string;title:string;dramaId:string;selectedEpisodes:number[];timeline:unknown[];qualityReport:unknown;ratio:"9:16"|"16:9"|"1:1";language:string}):Promise<FactoryProjectRecord>{const value=await request("/api/lumina/factory/episode-splice/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:input.id,title:input.title,drama_id:input.dramaId,selected_episodes:input.selectedEpisodes,timeline:input.timeline,quality_report:input.qualityReport,ratio:input.ratio,language:input.language})}) as Record<string,unknown>;return{id:String(value.id),status:String(value.status),version:Number(value.version||1)}}
export async function startFactoryRender(projectId:string,ratio:"9:16"|"16:9"|"1:1"="9:16"):Promise<FactoryRenderRecord>{const resolution=ratio==="16:9"?"1920x1080":ratio==="1:1"?"1080x1080":"1080x1920";const value=await request(`/api/lumina/factory/projects/${encodeURIComponent(projectId)}/renders`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({render_config:{format:"MP4",resolution,videoCodec:"H.264",audioCodec:"AAC",ratio}})}) as Record<string,unknown>;return{id:String(value.id),project:String(value.project),version:Number(value.version||1),status:String(value.status) as FactoryRenderRecord["status"],progress:0,stage:"queued",error:""}}
export async function getFactoryRender(id:string,signal?:AbortSignal):Promise<FactoryRenderRecord>{const value=await request(`/api/lumina/factory/renders/${encodeURIComponent(id)}`,{signal}) as Record<string,unknown>;const text=(field:string)=>typeof value[field]==="string"&&String(value[field]).trim()?String(value[field]):undefined;return{id:String(value.id),project:String(value.project),version:Number(value.version||1),status:String(value.status) as FactoryRenderRecord["status"],progress:Number(value.progress||0),stage:String(value.current_stage||""),error:String(value.error||""),errorKind:text("error_kind"),updated:text("updated"),retryOf:text("retry_of"),queuedAt:text("queued_at"),startedAt:text("started_at"),lastHeartbeatAt:text("last_heartbeat_at"),leaseUntil:text("lease_until"),nextAttemptAt:text("next_attempt_at"),previewUrl:text("preview_url"),outputUrl:text("output_url"),validation:value.validation}}
export async function retryFactoryRender(render:FactoryRenderRecord,input:{reason:string;idempotencyKey:string;overrideNonRetryable?:boolean;overrideReason?:string}):Promise<FactoryRenderRecord>{if(!render.updated)throw new Error("渲染任务缺少服务端更新版本，请先刷新状态");const value=await request(`/api/lumina/factory/renders/${encodeURIComponent(render.id)}/retry`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({reason:input.reason,idempotency_key:input.idempotencyKey,expected_status:render.status,expected_updated:render.updated,override_non_retryable:input.overrideNonRetryable===true,override_reason:input.overrideReason})}) as Record<string,unknown>;return{id:String(value.id),project:String(value.project),version:Number(value.version||render.version+1),status:String(value.status) as FactoryRenderRecord["status"],progress:0,stage:"queued",error:"",retryOf:String(value.retry_of||render.id)}}
export async function reviewFactoryRender(projectId:string,renderId:string,decision:"approved"|"rejected",note:string):Promise<void>{await request(`/api/lumina/factory/projects/${encodeURIComponent(projectId)}/review`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({render_id:renderId,decision,note})})}
export async function requestTransitionPreview(projectId:string):Promise<TransitionPreviewRecord>{const value=await request(`/api/lumina/factory/projects/${encodeURIComponent(projectId)}/transition-preview`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"}) as Record<string,unknown>;return{projectId:String(value.project||projectId),status:String(value.status||"queued") as TransitionPreviewRecord["status"],renderId:typeof value.id==="string"?value.id:undefined,previewVersion:Number(value.previewVersion||0)||undefined,transitionVersion:Number(value.transitionVersion||0)||undefined}}
export async function getTransitionPreview(projectId:string,signal?:AbortSignal):Promise<TransitionPreviewRecord>{const value=await request(`/api/lumina/factory/projects/${encodeURIComponent(projectId)}/transition-preview`,{signal}) as Record<string,unknown>;return{projectId:String(value.projectId||projectId),status:String(value.status||"idle") as TransitionPreviewRecord["status"],renderId:typeof value.renderId==="string"?value.renderId:undefined,previewUrl:typeof value.previewUrl==="string"?value.previewUrl:undefined,previewVersion:Number(value.previewVersion||0)||undefined,previewHash:typeof value.previewHash==="string"?value.previewHash:undefined,transitionVersion:Number(value.transitionVersion||0)||undefined,error:typeof value.error==="string"?value.error:undefined,transition:value.transition&&typeof value.transition==="object"?value.transition as Record<string,unknown>:undefined}}
export async function reviewTransitionPreview(projectId:string,decision:"approved"|"rejected",note:string,previewVersion:number,previewHash:string):Promise<Record<string,unknown>>{return await request(`/api/lumina/factory/projects/${encodeURIComponent(projectId)}/transition-review`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({decision,note,preview_version:previewVersion,preview_hash:previewHash})}) as Record<string,unknown>}
export async function exportFactoryRender(projectId:string,renderId:string,fileName:string):Promise<FactoryExportRecord>{return await request(`/api/lumina/factory/projects/${encodeURIComponent(projectId)}/export`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({render_id:renderId,file_name:fileName})}) as FactoryExportRecord}
export async function listFactoryHistory(signal?:AbortSignal):Promise<FactoryHistoryRecord[]>{const value=await request("/api/lumina/factory/history",{signal}) as {items?:FactoryHistoryRecord[]};return value.items??[]}
