"use client";

export type StoryMatchSegment = { episode:number;start:number;end:number;purpose?:string;highlightAssetId?:string;safeStart?:Record<string,unknown>;safeEnd?:Record<string,unknown>;evidence?:unknown[] };
export type HookStoryMatch = { id:string;hookId:string;dramaId:string;topics:string[];episodeScope:number[];scopeMode:string;targetDurationBand:string;matchContextHash:string;storyArc:{setup?:string;escalation?:string;payoff?:string;ending?:string};storyGraph:Record<string,unknown>;entryPoints:unknown[];completeness:Record<string,unknown>;calibration:Record<string,unknown>;productionGate:Record<string,unknown>;segments:StoryMatchSegment[];matchScore:number;storyScore:number;promiseFulfillmentScore:number;dimensionScores:Record<string,number>;evidence:unknown[];risks:string[];status:string;humanVideoApproved:boolean };
export type HookMatchDiagnostics = { outcomeStatus:"waiting_supplemental"|"partial"|"failed"|"no_candidates"|"ready"; funnel:{episodesRequested:number;rawCandidates:number;editableCandidates:number;productionCandidates:number;storyMatches:number;supplementalJobs:Record<string,number>};rejectionReasons:Array<{code:string;count:number}>;incomplete:boolean };
export type HookMatchJob = { id:string;status:"queued"|"running"|"succeeded"|"failed";progress:number;stage:string;error:string;diagnostics?:HookMatchDiagnostics };
const configuredUrl=typeof process!=="undefined"?process.env.NEXT_PUBLIC_POCKETBASE_URL:undefined;
const PB_URL=(configuredUrl||"http://127.0.0.1:8090").replace(/\/$/,"");
async function request(path:string,init?:RequestInit){const response=await fetch(`${PB_URL}${path}`,{cache:"no-store",...init});if(!response.ok){const value=await response.json().catch(()=>null) as {message?:string}|null;throw new Error(value?.message||`故事线匹配请求失败（HTTP ${response.status}）`)}return response.json()}
const list=(value:unknown)=>Array.isArray(value)?value:[];
const object=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
export async function startHookStoryMatch(hookId:string,dramaId:string,episodeScope:number[],topics:string[],scopeMode:"free_only"|"custom"="free_only",targetDurationSeconds=900,forceRetry=false):Promise<HookMatchJob>{const targetDurationBand=targetDurationSeconds>900?"15_25m":"5_15m";const value=await request("/api/lumina/hook-matching/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({hook_id:hookId,drama_id:dramaId,episode_scope:episodeScope,topics,scope_mode:scopeMode,target_duration_band:targetDurationBand,force_retry:forceRetry})}) as Record<string,unknown>;return{id:String(value.id),status:String(value.status) as HookMatchJob["status"],progress:Number(value.progress||0),stage:"queued",error:""}}
export async function setHookMatchSoftOverride(matchId:string,codes:Array<"story_score"|"understanding_cost"|"transition_difficulty">,enabled=true):Promise<void>{await request(`/api/lumina/hook-story-matches/${encodeURIComponent(matchId)}/soft-override`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({codes,enabled})})}
export async function approveHookMatchForProduction(matchId:string):Promise<void>{await request(`/api/lumina/hook-story-matches/${encodeURIComponent(matchId)}/human-production-approval`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"})}
export async function requestMoreEntryPoints(matchId:string):Promise<void>{await request("/api/lumina/entry-precision/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({match_id:matchId})})}
function parseDiagnostics(value:Record<string,unknown>):HookMatchDiagnostics|undefined{const raw=object(value.diagnostics),funnel=object(raw.funnel),supplemental=object(funnel.supplemental_jobs);const outcome=String(value.outcome_status||raw.outcome_status||"");if(!outcome)return undefined;return{outcomeStatus:outcome as HookMatchDiagnostics["outcomeStatus"],funnel:{episodesRequested:Number(funnel.episodes_requested||0),rawCandidates:Number(funnel.raw_candidates||0),editableCandidates:Number(funnel.editable_candidates||0),productionCandidates:Number(funnel.production_candidates||0),storyMatches:Number(funnel.story_matches||0),supplementalJobs:Object.fromEntries(Object.entries(supplemental).map(([key,count])=>[key,Number(count||0)]))},rejectionReasons:list(raw.rejection_reasons).map(item=>{const row=object(item);return{code:String(row.code||"unknown"),count:Number(row.count||0)}}),incomplete:Boolean(raw.incomplete)}}
export async function getHookMatchJob(id:string,signal?:AbortSignal):Promise<HookMatchJob>{const value=await request(`/api/collections/hook_match_jobs/records/${encodeURIComponent(id)}`,{signal}) as Record<string,unknown>;return{id:String(value.id),status:String(value.status) as HookMatchJob["status"],progress:Number(value.progress||0),stage:String(value.current_stage||""),error:String(value.error||""),diagnostics:parseDiagnostics(value)}}
export async function listHookStoryMatches(hookId:string,dramaId:string,signal?:AbortSignal):Promise<HookStoryMatch[]>{const filter=encodeURIComponent(`hook="${hookId}" && drama="${dramaId}"`),payload=await request(`/api/collections/hook_story_matches/records?perPage=100&sort=-match_score&filter=${filter}`,{signal}) as {items?:Array<Record<string,unknown>>};return(payload.items??[]).map(value=>{const dimensions=object(value.dimension_scores) as Record<string,number>;return{id:String(value.id),hookId:String(value.hook),dramaId:String(value.drama),topics:list(value.topics).map(String),episodeScope:list(value.episode_scope).map(Number),scopeMode:String(value.scope_mode||"free_only"),targetDurationBand:String(value.target_duration_band||"5_15m"),matchContextHash:String(value.match_context_hash||""),storyArc:object(value.story_arc),storyGraph:object(value.story_graph),entryPoints:list(value.entry_points),completeness:object(value.completeness),calibration:object(value.calibration),productionGate:object(value.production_gate),segments:list(value.segments).map(raw=>{const item=object(raw);return{episode:Number(item.episode),start:Number(item.start),end:Number(item.end),purpose:String(item.purpose||""),highlightAssetId:String(item.highlightAssetId||""),safeStart:object(item.safeStart),safeEnd:object(item.safeEnd),evidence:list(item.evidence)}}),matchScore:Number(value.match_score||0),storyScore:Number(value.story_score??value.match_score??0),promiseFulfillmentScore:Number(value.promise_fulfillment_score??dimensions.promise??0),dimensionScores:dimensions,evidence:list(value.evidence),risks:list(value.risks).map(raw=>{const risk=object(raw);return String(risk.description||risk.reason||raw)}),status:String(value.status||"candidate"),humanVideoApproved:object(object(value.soft_override).human_video_approval).overridden===true}})}
