"use client";

import { type FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { createInspirationMaterialVideoUrl, listInspirationMaterials, readVideoDuration, retryInspirationMaterialAnalysis, saveInspirationMaterial, submitInspirationReview, type InspirationMaterial, type InspirationMaterialType, type MaterialTag } from "../../lib/inspiration-material-store";
import styles from "./InspirationWorkspace.module.css";

export type InspirationTab = "feed" | "prototypes" | "analysis" | "review";
export type InspirationWorkspaceProps = { initialTab?: InspirationTab; onOpenFactory?: (materialId:string)=>void; onFavoriteChange?: (materialId:string,favorite:boolean)=>void; onAddMonitorSource?:()=>void };
type Material = InspirationMaterial;

const done=(item:Material)=>item.analysisStatus==="succeeded";
const fmt=(value:number)=>value>=10000000?`${(value/10000000).toFixed(1)}千万`:`${(value/10000).toFixed(value>=10000?0:1)}万`;
const duration=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(Math.round(seconds%60)).padStart(2,"0")}`;
const pct=(value:number)=>Math.round(value<=1?value*100:value);

export function InspirationWorkspace({initialTab="feed",onOpenFactory,onFavoriteChange,onAddMonitorSource}:InspirationWorkspaceProps){
  const [tab,setTab]=useState<InspirationTab>(initialTab),[materials,setMaterials]=useState<Material[]>([]),[selectedId,setSelectedId]=useState(""),[query,setQuery]=useState(""),[type,setType]=useState("全部类型"),[language,setLanguage]=useState("全部语种"),[uploadOpen,setUploadOpen]=useState(false),[toast,setToast]=useState(""),[error,setError]=useState(""),[favorites,setFavorites]=useState<string[]>([]);
  const refresh=async(signal?:AbortSignal)=>{try{setMaterials(await listInspirationMaterials(signal));setError("")}catch(reason){if(!signal?.aborted)setError(reason instanceof Error?reason.message:"素材读取失败")}};
  useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);const timer=window.setInterval(()=>void refresh(controller.signal),3000);return()=>{controller.abort();window.clearInterval(timer)}},[]);
  const completed=materials.filter(done),selected=completed.find(v=>v.id===selectedId)??completed[0];
  const reviewItems=completed.filter(v=>v.review!=="已通过"&&(v.analysisV2?.review.items.length||v.analysisV2?.review.status!=="已通过"));
  const prototypes=useMemo(()=>{const groups=new Map<string,Material[]>();for(const material of completed){for(const hook of material.analysisV2?.creative.hook?.mechanisms??[]){const bucket=groups.get(hook.code)??[];bucket.push(material);groups.set(hook.code,bucket)}}return [...groups].map(([code,items])=>({code,label:items[0].analysisV2?.creative.hook?.mechanisms.find(v=>v.code===code)?.label??code,items})).filter(group=>group.items.length>=2)},[completed]);
  const filtered=materials.filter(item=>(type==="全部类型"||item.type===type)&&(language==="全部语种"||item.language===language)&&(!query||`${item.title} ${item.platform} ${item.theme}`.toLowerCase().includes(query.toLowerCase())));
  const counts={feed:materials.length,prototypes:prototypes.length,analysis:completed.length,review:reviewItems.length};
  const flash=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)};
  const open=async(item:Material)=>{if(item.analysisStatus==="failed"){await retryInspirationMaterialAnalysis(item.id);flash("已重新加入分析队列");void refresh();return}if(done(item)){setSelectedId(item.id);setTab("analysis");return}flash(item.analysisStatus==="running"?`${item.analysisStage||"正在分析"} · ${Math.round(item.analysisProgress??0)}%`:"正在等待分析")};
  const favorite=(id:string)=>{const next=!favorites.includes(id);setFavorites(old=>next?[...old,id]:old.filter(v=>v!==id));onFavoriteChange?.(id,next)};
  return <section className={styles.workspace} aria-label="灵感大屏工作区">
    <header className={styles.header}><div><span className={styles.eyebrow}>市场素材情报中心</span><h1>灵感大屏</h1><p>独立分析外部买量成片，所有结论均来自当前素材证据。</p></div><div className={styles.headerActions}>{onAddMonitorSource&&<button className={styles.secondary} onClick={onAddMonitorSource}>＋ 添加监测源</button>}<button className={styles.primary} onClick={()=>setUploadOpen(true)}>＋ 手动上传爆款素材</button></div></header>
    <nav className={styles.tabs}>{([['feed','跑量素材'],['prototypes','钩子原型'],['analysis','素材分析'],['review','人工复核']] as const).map(([key,label])=><button key={key} className={tab===key?styles.activeTab:""} onClick={()=>setTab(key)}><span>{label}</span><em>{counts[key]}</em></button>)}</nav>
    {tab==="feed"&&<><div className={styles.stats}>{[["素材总数",materials.length],["已完成分析",completed.length],["钩子原型",prototypes.length],["长效素材",materials.filter(v=>v.days>=30).length],["待人工复核",reviewItems.length],["覆盖范围",`${new Set(materials.map(v=>v.market).filter(Boolean)).size} 市场 / ${new Set(materials.map(v=>v.language).filter(Boolean)).size} 语种`]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className={styles.toolbar}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题、平台或题材"/><select value={type} onChange={e=>setType(e.target.value)}><option>全部类型</option><option>正片剧集拼接</option><option>正片剧集解说</option><option>外搭钩子＋本剧正片</option></select><select value={language} onChange={e=>setLanguage(e.target.value)}><option>全部语种</option>{[...new Set(materials.map(v=>v.language))].map(v=><option key={v}>{v}</option>)}</select></div>{error?<State title="素材加载失败" detail={error}/>:filtered.length?<div className={styles.grid}>{filtered.map(item=><MaterialCard key={item.id} item={item} favorite={favorites.includes(item.id)} onFavorite={()=>favorite(item.id)} onOpen={()=>void open(item)}/>)}</div>:<State title={materials.length?"没有符合条件的素材":"还没有爆款素材"} detail={materials.length?"请调整筛选条件。":"使用右上角入口上传真实视频素材。"}/>}</>}
    {tab==="prototypes"&&(prototypes.length?<div className={styles.prototypeInsights}>{prototypes.map(group=><article key={group.code}><span className={styles.label}>已验证聚类 · {group.items.length} 个实例</span><h3>{group.label}</h3><p>仅由至少两个已完成分析的真实素材共同形成，不以单条素材推导规律。</p><div className={styles.chips}>{[...new Set(group.items.flatMap(v=>v.analysisV2?.creative.hook?.sensoryChannels.map(t=>t.label)??[]))].map(v=><span key={v}>{v}</span>)}</div><button onClick={()=>onOpenFactory?.(group.items[0].id)}>用真实实例进入内容工厂</button></article>)}</div>:<State title="暂无钩子原型" detail="至少两个已完成分析的真实素材形成相同钩子机制后才会建立原型。"/>)}
    {tab==="analysis"&&(selected?<Analysis item={selected} all={completed} onSelect={setSelectedId} onFactory={()=>onOpenFactory?.(selected.id)}/>:<State title="暂无分析结果" detail={materials.length?"素材完成 material-v2 真实分析后才会展示。":"请先上传真实视频素材。"}/>)}
    {tab==="review"&&(reviewItems.length?<Review items={reviewItems} onSaved={()=>void refresh()} flash={flash}/>:<State title="暂无待复核项" detail="仅展示模型明确标为待复核或置信度不足的真实标签。"/>)}
    {uploadOpen&&<Upload onClose={()=>setUploadOpen(false)} onSaved={item=>{setMaterials(old=>[item,...old.filter(v=>v.id!==item.id)]);setUploadOpen(false);flash("素材已保存并进入分析队列");void refresh()}}/>}{toast&&<div className={styles.toast}>✓ {toast}</div>}
  </section>
}

function MaterialCard({item,favorite,onFavorite,onOpen}:{item:Material;favorite:boolean;onFavorite:()=>void;onOpen:()=>void}){
  const video=useRef<HTMLVideoElement>(null),url=createInspirationMaterialVideoUrl(item),[playError,setPlayError]=useState("");
  const v2=item.analysisV2,hook=v2?.creative.hook?.mechanisms[0]?.label,tLevel=v2?.creative.tLevel?.label,structure=v2?.creative.timeline.slice(0,3).map(v=>v.label).join(" → ");
  return <article className={styles.card}><div className={`${styles.cover} ${styles[item.color]}`}>{url&&<video ref={video} className={styles.materialVideo} src={url} preload="metadata" controls onError={()=>setPlayError("浏览器无法解码该视频，请使用 H.264/AAC MP4")}/>}<span className={styles.source}>{item.source} · {item.platform}</span><em>{item.media?duration(item.media.duration):"无片源"}</em><button className={`${styles.favorite} ${favorite?styles.favorited:""}`} onClick={onFavorite}>{favorite?"♥":"♡"}</button>{playError&&<div className={styles.playbackError}>{playError}</div>}</div><div className={styles.cardBody}><div className={styles.tags}>{tLevel&&<span>{tLevel}</span>}{hook&&<span>{hook}</span>}<span>{item.language}</span></div><h3>{item.title}</h3><p>{item.analysisStatus==="running"?`${item.analysisStage||"正在处理"} · ${Math.round(item.analysisProgress??0)}%`:item.analysisStatus==="failed"?item.analysisError||"分析失败":structure||item.analysis}</p><dl><div><dt>曝光</dt><dd>{fmt(item.exposure)}</dd></div><div><dt>跑量</dt><dd>{item.days} 天</dd></div><div><dt>复核</dt><dd>{item.review}</dd></div></dl><div className={styles.cardFooter}><span>{item.captured}</span><button onClick={onOpen}>{done(item)?"进入分析 →":item.analysisStatus==="failed"?"重新分析":`${Math.round(item.analysisProgress??0)}%`}</button></div></div></article>
}

function Analysis({item,all,onSelect,onFactory}:{item:Material;all:Material[];onSelect:(id:string)=>void;onFactory:()=>void}){
  const data=item.analysisV2;if(!data)return <State title="结果契约待升级" detail="该素材已完成旧版分析，但尚未生成 material-v2 四层标签。请重新分析。"/>;
  const tagGroups:[string,MaterialTag[]][]=[["题材",data.content.genres],["主题",data.content.themes],["人物",data.content.characters],["关系",data.content.relations],["情绪",data.content.emotions],["冲突",data.content.conflicts],["情节点",data.content.storyBeats],["场景",data.content.scenes]];
  return <div className={styles.analysisV2}><div className={styles.instancePicker}><label>分析实例<select value={item.id} onChange={e=>onSelect(e.target.value)}>{all.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label><span>契约 <b>material-v2</b></span><button className={styles.primary} onClick={onFactory}>进入内容工厂 →</button></div>
    <section className={styles.v2Section}><h2>证据层</h2><p>所有结论仅追溯到当前外部素材，不要求匹配完整剧集。</p>{data.evidence.length?<div className={styles.evidenceList}>{data.evidence.map((v,i)=><article key={v.id??i}><b>{v.kind.toUpperCase()} · {duration(v.start)}–{duration(v.end)}</b><span>{v.translation||v.text||"画面证据"}</span><small>{pct(v.confidence)}% · {v.verification||"未标记"}</small></article>)}</div>:<InlineEmpty text="没有可展示的证据记录"/>}</section>
    <section className={styles.v2Section}><h2>素材内容理解</h2>{data.content.summary&&<blockquote>{data.content.summary}</blockquote>}<p>内容完整性：{data.content.completeness||"未判断"}</p><div className={styles.tagGroups}>{tagGroups.filter(([,tags])=>tags.length).map(([label,tags])=><div key={label}><b>{label}</b><TagList tags={tags}/></div>)}</div>{!tagGroups.some(([,tags])=>tags.length)&&<InlineEmpty text="没有内容标签"/>}</section>
    <section className={styles.v2Section}><h2>买量创意结构</h2><div className={styles.summaryCards}><article><span>素材形态</span><b>{data.creative.materialType?.label||"未判断"}</b></article><article><span>T 级</span><b>{data.creative.tLevel?.label||"未判断"}</b></article><article><span>钩子机制</span><b>{data.creative.hook?.mechanisms.map(v=>v.label).join("、")||"未判断"}</b></article></div>{data.creative.timeline.length?<div className={styles.realTimeline}>{data.creative.timeline.map((v,i)=><article key={`${v.code}-${i}`}><b>{duration(v.start)}–{duration(v.end)} · {v.label}</b><span>{v.description||""}</span><small>{pct(v.confidence??0)}%</small></article>)}</div>:<InlineEmpty text="没有结构时间轴"/>}<div className={styles.tagGroups}><div><b>包装</b><TagList tags={data.creative.packaging}/></div><div><b>过渡</b><TagList tags={data.creative.transitions}/></div><div><b>感官通道</b><TagList tags={data.creative.hook?.sensoryChannels??[]}/></div></div></section>
    <section className={styles.v2Section}><h2>灵感与复用价值</h2>{data.value.scores.length?<div className={styles.scoreGrid}>{data.value.scores.map(v=><article key={v.code}><span>{v.label}</span><strong>{Math.round(v.score)}</strong><i><em style={{width:`${Math.max(0,Math.min(100,v.score))}%`}}/></i><small>{v.reason||"无评分说明"}</small></article>)}</div>:<InlineEmpty text="没有价值评分"/>}<div className={styles.adviceGrid}><Advice title="值得借鉴" items={data.value.inspirations}/><Advice title="不建议复制" items={data.value.avoid}/><Advice title="适合题材" items={data.value.suitableGenres}/><Advice title="适合受众" items={data.value.suitableAudiences}/></div></section>
  </div>
}

function Review({items,onSaved,flash}:{items:Material[];onSaved:()=>void;flash:(s:string)=>void}){const [selectedId,setSelectedId]=useState(items[0]?.id??""),[note,setNote]=useState(""),[saving,setSaving]=useState(false);const item=items.find(v=>v.id===selectedId)??items[0];const uncertain=[...(item.analysisV2?.review.items??[])];for(const group of Object.values(item.analysisV2?.content??{})){if(Array.isArray(group))for(const tag of group as MaterialTag[])if(tag.verification==="needs_review"&&!uncertain.some(v=>v.id===tag.code))uncertain.push({id:tag.code,field:"content",label:tag.label,reason:"模型标记为待复核",confidence:tag.confidence})}const submit=async(status:"已通过"|"已修改"|"退回重分析")=>{setSaving(true);try{await submitInspirationReview(item.id,status,note);flash(status==="退回重分析"?"已退回并重新入队":"复核结果已持久保存");onSaved()}catch(reason){flash(reason instanceof Error?reason.message:"保存失败")}finally{setSaving(false)}};return <div className={styles.reviewV2}><aside>{items.map(v=><button className={v.id===item.id?styles.selected:""} key={v.id} onClick={()=>setSelectedId(v.id)}><b>{v.title}</b><small>{v.analysisV2?.review.items.length??0} 个待确认项</small></button>)}</aside><section><h2>人工复核</h2><p>只复核证据不足、不确定或冲突的标签。</p>{uncertain.length?<div className={styles.reviewItems}>{uncertain.map(v=><article key={v.id}><b>{v.label}</b><span>{v.reason||v.field}</span><small>置信度 {pct(v.confidence??0)}%</small>{v.proposedValue&&<em>建议：{v.proposedValue}</em>}</article>)}</div>:<InlineEmpty text="模型未列出具体待复核标签，可直接确认整体结果"/>}<label className={styles.reviewNote}>复核说明<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="记录修改依据或退回原因"/></label><div className={styles.reviewActions}><button disabled={saving} onClick={()=>void submit("退回重分析")}>退回重分析</button><button disabled={saving} onClick={()=>void submit("已修改")}>修改后通过</button><button className={styles.primary} disabled={saving} onClick={()=>void submit("已通过")}>确认通过</button></div></section></div>}

function Upload({onClose,onSaved}:{onClose:()=>void;onSaved:(item:Material)=>void}){const [file,setFile]=useState<File|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false);const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!file){setError("请选择视频文件");return}setSaving(true);try{const form=new FormData(event.currentTarget),videoDuration=await readVideoDuration(file);const input={title:String(form.get("title")||file.name.replace(/\.[^.]+$/, "")),type:String(form.get("type")) as InspirationMaterialType,source:"外部" as const,platform:String(form.get("platform")||"手动上传"),market:String(form.get("market")||"未知市场"),language:String(form.get("language")||"未知语种"),theme:String(form.get("theme")||"待分析"),exposure:Math.max(0,Number(form.get("exposure")||0)),days:Math.max(0,Number(form.get("days")||0)),duration:videoDuration};onSaved(await saveInspirationMaterial(input,file))}catch(reason){setError(reason instanceof Error?reason.message:"素材保存失败");setSaving(false)}};return <div className={styles.modalBackdrop}><form className={styles.uploadModal} onSubmit={submit}><header><div><span className={styles.eyebrow}>EXTERNAL MATERIAL</span><h2>手动上传爆款素材</h2></div><button type="button" onClick={onClose}>×</button></header><div className={styles.uploadFields}><label className={styles.fullField}>视频文件<input type="file" accept="video/*" required onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>素材标题<input name="title" placeholder="默认使用文件名"/></label><label>素材类型<select name="type" defaultValue="外搭钩子＋本剧正片"><option>正片剧集拼接</option><option>正片剧集解说</option><option>外搭钩子＋本剧正片</option></select></label><label>平台<input name="platform"/></label><label>市场<input name="market"/></label><label>语种<input name="language"/></label><label>题材<input name="theme"/></label><label>真实曝光量<input name="exposure" type="number" min="0"/></label><label>真实跑量天数<input name="days" type="number" min="0"/></label></div>{error&&<p className={styles.uploadError}>{error}</p>}<footer><button type="button" onClick={onClose}>取消</button><button className={styles.primary} disabled={saving}>{saving?"正在保存…":"保存并加入分析队列"}</button></footer></form></div>}

function TagList({tags}:{tags:MaterialTag[]}){return tags.length?<div className={styles.v2Tags}>{tags.map((tag,i)=><span key={`${tag.code}-${i}`} title={`置信度 ${pct(tag.confidence)}% · ${tag.verification||"未标记"}`}>{tag.label}<small>{pct(tag.confidence)}%</small></span>)}</div>:<small>暂无</small>}
function Advice({title,items}:{title:string;items:string[]}){return <article><b>{title}</b>{items.length?<ul>{items.map((v,i)=><li key={i}>{v}</li>)}</ul>:<small>暂无真实结论</small>}</article>}
function InlineEmpty({text}:{text:string}){return <div className={styles.inlineEmpty}>{text}</div>}
function State({title,detail}:{title:string;detail:string}){return <div className={styles.statePanel}><i>◇</i><h3>{title}</h3><p>{detail}</p></div>}

export default InspirationWorkspace;
