'use strict';
const $ = id => document.getElementById(id);
let editing = null;
async function api(path, data) {
  const response = await fetch(path, {method:data === undefined ? 'GET':'POST', credentials:'same-origin', headers:data === undefined ? {}:{'Content-Type':'application/json'}, body:data === undefined ? undefined:JSON.stringify(data)});
  const value = await response.json();
  if (!response.ok) {const error = new Error(value.message || '操作失败，请重试');error.status=response.status;throw error;}
  return value;
}
function returnPath() {const target=new URLSearchParams(location.search).get('return_to') || '/';try {const u=new URL(target,location.origin);return u.origin===location.origin && target.startsWith('/') && !target.startsWith('//') && !['/login','/register'].includes(u.pathname) ? u.pathname+u.search+u.hash:'/';}catch{return '/';}}
function bindForm(id, action) {const form=$(id);form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('[type=submit]');const message=form.querySelector('.message');message.textContent='';button.disabled=true;try{await action(Object.fromEntries(new FormData(form)),form);}catch(error){message.textContent=error.message;}finally{button.disabled=false;}});}
document.querySelector('.reveal').addEventListener('click',event=>{const input=$('login-form').elements.password;input.type=input.type==='password'?'text':'password';event.target.textContent=input.type==='password'?'显示':'隐藏';event.target.setAttribute('aria-label',input.type==='password'?'显示密码':'隐藏密码');});
bindForm('login-form',async (data,form)=>{await api('/auth/login',{...data,remember:form.elements.remember.checked});location.replace(returnPath());});
bindForm('register-form',async data=>{if(data.password!==data.confirm)throw new Error('两次输入的密码不一致');await api('/auth/register',data);sessionStorage.setItem('lumina.registered.username',data.username);location.replace('/login?registered=1');});
bindForm('password-form',async data=>{if(data.password!==data.confirm)throw new Error('两次输入的新密码不一致');await api('/auth/password',data);location.replace('/login?changed=1');});
$('logout').addEventListener('click',async()=>{try{await api('/auth/logout',{});location.replace('/login');}catch(error){$('identity').textContent=error.message;}});
function openUser(user=null){editing=user;const form=$('user-form');form.reset();$('dialog-title').textContent=user?'编辑账号':'创建账号';$('username-label').hidden=!!user;form.elements.username.required=!user;form.elements.username.value=user?.username || '';form.elements.name.value=user?.name || '';form.elements.role.value=user?.role || 'member';form.elements.active.checked=!!user?.active;form.elements.password.required=!user;$('active-label').hidden=!user;$('edit-hint').hidden=!user;form.querySelector('.message').textContent='';$('user-dialog').showModal();}
$('new-user').addEventListener('click',()=>openUser());$('cancel-user').addEventListener('click',()=>$('user-dialog').close());
async function loadUsers(){const {users}=await api('/auth/users');$('user-list').replaceChildren();for(const user of users){const row=document.createElement('div');row.className='user-row';const identity=document.createElement('div');const name=document.createElement('b');name.textContent=user.name;const username=document.createElement('small');username.textContent=user.username;identity.append(name,username);const role=document.createElement('span');role.textContent=user.role==='admin'?'管理员':'成员';const status=document.createElement('span');status.className='badge'+(user.active?'':' off');status.textContent=user.active?'已启用':'待启用 / 已停用';const edit=document.createElement('button');edit.className='secondary';edit.textContent='编辑';edit.addEventListener('click',()=>openUser(user));row.append(identity,role,status,edit);$('user-list').append(row);}}
bindForm('user-form',async(data,form)=>{if(editing){if(!data.password)delete data.password;data.active=form.elements.active.checked;}await api(editing?'/auth/users/'+editing.id:'/auth/users',data);$('user-dialog').close();await loadUsers();});
(async()=>{try{const {user}=await api('/auth/me');if(['/login','/register'].includes(location.pathname)){location.replace(returnPath());return;}$('account').hidden=false;$('identity').textContent=user.name+' · '+user.username+' · '+(user.role==='admin'?'管理员':'成员');if(user.role==='admin'){$('admin').hidden=false;await loadUsers();}}catch(error){if(error.status!==401){$('login').hidden=false;$('login-form').querySelector('.message').textContent=error.message;return;}if(location.pathname==='/register'){$('register').hidden=false;$('back').hidden=true;return;}if(location.pathname!=='/login'){location.replace('/login?return_to=%2Faccount');return;}$('login').hidden=false;$('back').hidden=true;if(new URLSearchParams(location.search).has('registered')){const message=$('login-form').querySelector('.message');message.classList.add('success');const username=sessionStorage.getItem('lumina.registered.username') || '';$('login-form').elements.username.value=username;message.textContent='注册成功'+(username?'，登录账号：'+username:'')+'。请等待管理员启用；姓名不是登录账号。';}if(new URLSearchParams(location.search).has('changed')){const message=$('login-form').querySelector('.message');message.classList.add('success');message.textContent='密码已更新，请使用新密码登录。';}}})();
