/// <reference path="../pb_data/types.d.ts" />

routerAdd("GET", "/api/lumina/local-ui/collections/{collection}/records", (e) => { const h=e.requestInfo().headers,o=String(h.origin||"");if($os.getenv("LUMINA_UI_MODE")!=="local-loopback"||String(h["x-lumina-ui"]||h["X-Lumina-Ui"]||(e.request&&e.request.header?e.request.header.get("x-lumina-ui"):"")||"")!=="local"||(o&&!/^https?:\/\/(localhost|127\.0\.0\.1):(300[01]|8090)$/i.test(o)))throw new ForbiddenError("Local UI gateway required");return e.json(200,require(`${__hooks}/local_ui_gateway_helpers.js`).listRecords(e)); });
routerAdd("GET", "/api/lumina/local-ui/collections/{collection}/records/{id}", (e) => { const h=e.requestInfo().headers,o=String(h.origin||"");if($os.getenv("LUMINA_UI_MODE")!=="local-loopback"||String(h["x-lumina-ui"]||h["X-Lumina-Ui"]||(e.request&&e.request.header?e.request.header.get("x-lumina-ui"):"")||"")!=="local"||(o&&!/^https?:\/\/(localhost|127\.0\.0\.1):(300[01]|8090)$/i.test(o)))throw new ForbiddenError("Local UI gateway required");return e.json(200,require(`${__hooks}/local_ui_gateway_helpers.js`).getRecord(e)); });
routerAdd("POST", "/api/lumina/local-ui/collections/{collection}/records", (e) => {
  const h=e.requestInfo().headers,o=String(h.origin||"");if($os.getenv("LUMINA_UI_MODE")!=="local-loopback"||String(h["x-lumina-ui"]||h["X-Lumina-Ui"]||(e.request&&e.request.header?e.request.header.get("x-lumina-ui"):"")||"")!=="local"||(o&&!/^https?:\/\/(localhost|127\.0\.0\.1):(300[01]|8090)$/i.test(o)))throw new ForbiddenError("Local UI gateway required");
  const collection=String(e.request.pathValue("collection"));
  if(!["dramas","drama_episodes","ad_materials"].includes(collection))throw new ForbiddenError("Local UI collection is not writable");
  const contentType=String(e.request&&e.request.header?e.request.header.get("content-type"):"");
  const uploaded={};
  if(/^multipart\/form-data(?:;|$)/i.test(contentType))["poster","video"].forEach((field)=>{try{const pair=e.request.formFile(field);if(pair&&pair[0])pair[0].close();uploaded[field]=pair&&pair[1]?[$filesystem.fileFromMultipart(pair[1])]:[];}catch(_){uploaded[field]=[];}});
  const multipartFields={dramas:["external_id","title","cn","genre","language","total_episodes","free_episodes","copyright_status","parse_state","parse_config","analysis","source_type","source_platform","source_record_id","acquisition_method","external_cover_url","source_metadata"],drama_episodes:["drama","episode_number","original_name","mime_type","byte_size","duration_seconds","analysis_status","analysis_progress","analysis_error","analysis_result"],ad_materials:["title","type","source","platform","market","language","theme","exposure","days","original_name","mime_type","byte_size","duration_seconds","analysis_status","analysis_progress","analysis_error","analysis_result","prototype","review_status","analysis_schema_version","analysis_stage","segment_count","hook_count","creative_tier","material_format","review_flags","prototype_inputs","source_attribution","content_hash","source_url","rights_status","intake_status","intake_batch_id","intake_error","source_identity_hash"]};
  const body=/^multipart\/form-data(?:;|$)/i.test(contentType)?Object.fromEntries(multipartFields[collection].map((key)=>[key,e.request.formValue(key)]).filter(([,value])=>value!=="")):(e.requestInfo().body||{}),record=new Record(e.app.findCollectionByNameOrId(collection));
  Object.keys(body).forEach((key)=>{if(!["id","collectionId","collectionName","created","updated","poster","video"].includes(key))record.set(key,body[key]);});
  ["poster","video"].forEach((field)=>{const files=uploaded[field]||[];if(files.length>1)throw new BadRequestError(`Only one ${field} file is allowed`);if(files.length===1)record.set(field,files[0]);});
  e.app.save(record);
  return e.json(201,record.publicExport());
});

routerAdd("POST", "/api/lumina/local-ui/import-material-file", (e) => {
  const h = e.requestInfo().headers, o = String(h.origin || "");
  if ($os.getenv("LUMINA_UI_MODE") !== "local-loopback" || String(h["x-lumina-ui"] || h["X-Lumina-Ui"] || (e.request && e.request.header ? e.request.header.get("x-lumina-ui") : "") || "") !== "local" || (o && !/^https?:\/\/(localhost|127\.0\.0\.1):(300[01]|8090)$/i.test(o))) throw new ForbiddenError("Local UI gateway required");
  return e.json(201, require(`${__hooks}/local_ui_gateway_helpers.js`).importMaterialFile(e));
});
routerAdd("PATCH", "/api/lumina/local-ui/collections/{collection}/records/{id}", (e) => { const h=e.requestInfo().headers,o=String(h.origin||"");if($os.getenv("LUMINA_UI_MODE")!=="local-loopback"||String(h["x-lumina-ui"]||h["X-Lumina-Ui"]||(e.request&&e.request.header?e.request.header.get("x-lumina-ui"):"")||"")!=="local"||(o&&!/^https?:\/\/(localhost|127\.0\.0\.1):(300[01]|8090)$/i.test(o)))throw new ForbiddenError("Local UI gateway required");const saved=require(`${__hooks}/local_ui_gateway_helpers.js`).updateRecord(e);return e.json(saved.status,saved.record); });
routerAdd("DELETE", "/api/lumina/local-ui/collections/{collection}/records/{id}", (e) => { const h=e.requestInfo().headers,o=String(h.origin||"");if($os.getenv("LUMINA_UI_MODE")!=="local-loopback"||String(h["x-lumina-ui"]||h["X-Lumina-Ui"]||(e.request&&e.request.header?e.request.header.get("x-lumina-ui"):"")||"")!=="local"||(o&&!/^https?:\/\/(localhost|127\.0\.0\.1):(300[01]|8090)$/i.test(o)))throw new ForbiddenError("Local UI gateway required");require(`${__hooks}/local_ui_gateway_helpers.js`).deleteRecord(e);return e.noContent(204); });
routerAdd("GET", "/api/lumina/local-ui/files/{collection}/{id}/{filename}", (e) => { const h=e.requestInfo().headers,o=String(h.origin||"");if($os.getenv("LUMINA_UI_MODE")!=="local-loopback"||String(h["x-lumina-ui"]||h["X-Lumina-Ui"]||(e.request&&e.request.header?e.request.header.get("x-lumina-ui"):"")||"")!=="local"||(o&&!/^https?:\/\/(localhost|127\.0\.0\.1):(300[01]|8090)$/i.test(o)))throw new ForbiddenError("Local UI gateway required");return require(`${__hooks}/local_ui_gateway_helpers.js`).getFile(e); });
